const gereqsOptions = [
    { value: "", viewValue: "All" },
    { value: "ALS-A", viewValue: "ALS-A" },
    { value: "ALS-L", viewValue: "ALS-L" },
    { value: "AQR", viewValue: "AQR" },
    { value: "BTS-B", viewValue: "BTS-B" },
    { value: "BTS-T", viewValue: "BTS-T" },
    { value: "EIN", viewValue: "EIN" },
    { value: "FOL-C", viewValue: "FOL-C" },
    { value: "FOL-F", viewValue: "FOL-F" },
    { value: "FOL-G", viewValue: "FOL-G" },
    { value: "FOL-J", viewValue: "FOL-J" },
    { value: "FOL-K", viewValue: "FOL-K" },
    { value: "FOL-L", viewValue: "FOL-L" },
    { value: "FOL-N", viewValue: "FOL-N" },
    { value: "FOL-R", viewValue: "FOL-R" },
    { value: "FOL-S", viewValue: "FOL-S" },
    { value: "FYW", viewValue: "FYW" },
    { value: "HBS", viewValue: "HBS" },
    { value: "HWC", viewValue: "HWC" },
    { value: "IST", viewValue: "IST" },
    { value: "MCD", viewValue: "MCD" },
    { value: "MCG", viewValue: "MCG" },
    { value: "ORC", viewValue: "ORC" },
    { value: "SED", viewValue: "SED" },
    { value: "SPM", viewValue: "SPM" },
    { value: "WRI", viewValue: "WRI" },
]

export default gereqsOptions